return {
  "folke/neodev.nvim",
  "folke/which-key.nvim",
  { "folke/neoconf.nvim", cmd = "Neoconf" },
}

-- local plugins = {
    -- {
    --   "williamboman/mason.nvim",
    --     config = function() 
    --         require("mason").setup({})
    --     end,
    -- },
    -- {
    --     "williamboman/mason-lspconfig.nvim",
    --     config = function() 
    --         require("mason-lspconfig").setup()
    --     end,
    -- },
	-- {
	-- 	'neovim/nvim-lspconfig',
  --       config = function() 
  --           require("mason").setup({})
  --           require("mason-lspconfig").setup()
  --           require("plugins.lsp.lspconfig")
  --       end,
	-- },
    -- {
    --     "pocco81/auto-save.nvim"
    -- },
	-- {
  --       "hrsh7th/nvim-cmp",
  --       dependencies = {
  --           "hrsh7th/cmp-buffer", "hrsh7th/cmp-nvim-lsp",
  --           'quangnguyen30192/cmp-nvim-ultisnips', 'hrsh7th/cmp-nvim-lua',
  --           'octaltree/cmp-look', 'hrsh7th/cmp-path', 'hrsh7th/cmp-calc',
  --           'f3fora/cmp-spell', 'hrsh7th/cmp-emoji'
  --       },
  --       config = function()
  --           require("plugins.cmp")
  --       end,
	-- },
    -- {
    --     "zbirenbaum/copilot.lua",
    --     cmd = "Copilot",
    --     event = "InsertEnter",
    --     config = function()
    --         require("copilot").setup({
    --             suggestion = { enabled = false },
    --             panel = { enabled = false },
    --         })
    --     end,
    -- },
    -- {
    --     "zbirenbaum/copilot-cmp",
    --     cmd = "Copilot",
    --     config = function()
    --         require("copilot_cmp").setup()
    --     end,
    -- },
    -- {
    --     'onsails/lspkind-nvim'
    -- },
    -- {
    --     'windwp/nvim-autopairs',
    --     event = "InsertEnter",
    --     opts = {} -- this is equalent to setup({}) function
    -- },
             -- {
             --     'jiangmiao/auto-pairs'
             -- },
    -- {
    --     'folke/tokyonight.nvim',
    --     lazy = false,
    --     priority = 1000,
    --     opts = {},
    -- },
    -- {
    --     "nvim-lualine/lualine.nvim",
    --     config = function()
    --         require("plugins.lualine")
    --     end
    -- },
    -- {
    --     'nvim-telescope/telescope.nvim', version = '0.1.5',
    --     dependencies = { 'nvim-lua/plenary.nvim' }
    -- },
    -- {
    --     "nvim-treesitter/nvim-treesitter",
    --     build = ":TSUpdate",
    --     config = function () 
    --       local configs = require("nvim-treesitter.configs")

    --       configs.setup({
    --           ensure_installed = { "lua", "vim", "vimdoc", "query", "tsx", "go", "javascript", "typescript", "html", "go", "gomod", "gowork", "gosum" },
    --           sync_install = false,
    --           highlight = { enable = true },
    --           indent = { enable = true },  
    --         })
    --     end
    -- },
    -- {
    --     'nvim-tree/nvim-tree.lua',
    --     dependencies = { 'nvim-tree/nvim-web-devicons' },
    --     config = function()
    --         require("plugins.nvim-tree")
    --     end,
    -- },
    -- {
	  --   "kylechui/nvim-surround",
    --     version = "*", -- Use for stability; omit to use `main` branch for the latest features
    --     event = "VeryLazy",
    --     config = function()
    --         require("nvim-surround").setup({
    --             -- Configuration here, or leave empty to use defaults
    --         })
    --     end,
    -- },
    -- {
    --     'nvimdev/lspsaga.nvim',
    --     config = function()
    --         require('lspsaga').setup({})
    --     end,
    --     dependencies = {
    --         'nvim-treesitter/nvim-treesitter', -- optional
    --         'nvim-tree/nvim-web-devicons'     -- optional
    --     },
    -- }
-- }

-- local opts = {
--   performance = {
--     rtp = {
--       disabled_plugins = {
--         -- 'gzip',
--         -- 'matchit',
--         --'matchparen',
--         -- 'netrwPlugin',
--         -- 'tarPlugin',
--         -- 'tohtml',
--         -- 'tutor',
--         -- 'zipPlugin',
--       },
--     },
--   },
-- }

